version: '3'

networks:
  appnet:

volumes:
  appvol:

services:
  mydb:
    image: clintontay/mysqldb:v2
    build: 
      context: ./database
    environment:
    - MYSQL_ROOT_PASSWORD=changeit
    networks:
    - appnet
    volumes:
    - appvol:/var/lib/mysql

  myserver:
    image: clintontay/server:v2
    build:
      context: ./server
    environment:
    - DB_HOST=mydb
    ports:
    - 80:3000
    networks:
    - appnet