apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mysqldb-pvc
  annotations:
    volume.beta.kuberneties.io/storage-provisioner: "dobs.csi.digitalocean.com"

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage

  #kubectl get storageclasses.storage.k8s.io to get storageClassName and provisioner