# Default values for mlapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: balanus/mlapp
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

