---
apiVersion: v1
kind: Namespace

metadata:
  name: myns
  labels:
    version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: myns

data:
  db_host: northwind-svc.myns.svc.cluster.local
  db_user: root

---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: myns

data:
  db_password: aGVsbG93b3JsZA==


