---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: northwind-deploy
  namespace: myns
  labels:
    name: northwind
    version: v1

spec:
  # number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: northwinddb
      version: v1
  template:
    #pod template
    metadata:
      name: northwind-pod
      labels:
        name: northwinddb
        version: v1
    spec:
      containers:
      - name: northwind-container
        image: clintontay/mysqldb:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports:
        - name: mysql-port
          containerPort: 3306
---
apiVersion: v1
kind: Service

metadata: 
  name: northwind-svc
  namespace: myns
  labels:
    name: northwind-svc
    version: v1

spec: 
  type: ClusterIP
  selector:
    name: northwinddb
    version: v1
  ports:
  - name: mysqlsvchttp
    port: 3306
    targetPort: mysql-port

