---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwserver-deploy
  namespace: myns
  labels:
    name: nwserver
    version: v1

spec:
  # number of pods
  replicas: 3
  selector:
    matchLabels:
      name: nwserver
      version: v1
  template:
    #pod template
    metadata:
      name: server-pod
      labels:
        name: nwserver
        version: v1
    spec:
      containers:
      - name: nwserver-container
        image: clintontay/server:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nwapp-config
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nwapp-config
              key: db_user
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: server-port
          containerPort: 3000
---
apiVersion: v1
kind: Service

metadata: 
  name: nwserver-svc
  namespace: myns
  labels:
    name: nwserver-svc
    version: v1

spec: 
  type: LoadBalancer
  selector:
    name: nwserver
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: server-port


